config/routes.rb
Articulus::Application.routes.draw do

  resources :articles do
    resources :comments
  end
  devise_for :users
  match 'users/:id' => 'users#show', as: 'user'
  root :to => "home#index"

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  # Fields
  field :title, type: String
  field :content, type: String

  # Associations
  belongs_to :user
  embeds_many :comments

  # Validations
  validates_presence_of :title, :content, :user
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  # Fields
  field :text, type: String
  field :user, type: String  # Here :user is actually username

  # Association
  embedded_in :article, inverse_of: :comments

  # Validation
  validates_presence_of :text, :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Additional Fields
  field :username
  field :_id, type: String, default: ->{ username }

  # Associations
  has_many :articles

  # Validations
  validates_presence_of :username
  validates_uniqueness_of :username, :email, case_sensitive: false

  attr_accessible :username, :email, :password, :password_confirmation, :remember_me


  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  # For user_path helper method
  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(title: params[:article][:title], content: params[:article][:content], user_id: current_user._id)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(title: params[:article][:title], content: params[:article][:content])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
	@article = Article.find(params[:article_id])
	@comment = @article.comments.create!(text: params[:comment][:text], user: current_user._id)
	redirect_to @article, notice: "Comment Created"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, input_html: { class: 'span8' } %>
    <%= f.input :content, as: :text, input_html: { class: 'span8' }, rows: "10" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>

    <h3><%= link_to article.title, article %></h3>
    <p><%= article.created_at %>. By: <%= link_to article.user.username, article.user %>. <%= article.comments.size %> Comments.
    <div class="well">
      <%= article.content %>
    </div>
    <hr></hr>
<% end %>

<br />

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <h2><%= @article.title %></h2>
</p>
<p>
  <%= @article.created_at %>, By: <%= link_to @article.user.username, @article.user %>
<div class="well">
  <%= @article.content %>
</div>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', articles_path %>

<br/>
<h4>New Comment</h4>
<br/>

<%= simple_form_for([@article, Comment.new]) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :text, as: :text, input_html: { class: 'span6' , style: 'height: 60px'}, label: false %>
  </div>

  <%= f.button :submit %>
<% end %>

<% if @article.comments.size > 0 %>
  <h3>Comments</h3>
  <% for comment in @article.comments %>
  <p class="well">
  	<%= comment.text %><br/>
  	By: <%= link_to comment.user, user_path(comment.user) %>
  </p>
  <% end %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/home/index.html.erb
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Articulus", root_path, :class => 'brand' %>
<% if user_signed_in? %>
  <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'Articles', articles_path %></li>
  <li class="divider-vertical"></li>
  <li><%= link_to 'New Article', new_article_path %></li>
  </ul>
<% end %>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li><%= link_to('Edit account', edit_user_registration_path) %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
  <% else %>
    <li><%= link_to('Sign up', new_user_registration_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Articulus" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", media: "all",  debug: false  %>
    <%= javascript_include_tag "application",  debug: false  %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/show.html.erb
<h1>User</h1>
<p>User: <%= @user.username %></p>